### ISSUE TITLE
help me

### ISSUE THREAD

**Issue by DarthArnettJr** [QueenOfSquiggles/the-last-sword-you-will-ever-need-mod#3]
I need to fix this error code.
Incompatible mod set!
net.fabricmc.loader.impl.FormattedException: Mod resolution encountered an incompatible mod set!
A potential solution has been determined:
	 - Replace 'OpenJDK 64-Bit Server VM' (java) 16 with version 17 or later.
Unmet dependency listing:
	 - Mod 'The Last Sword You Will Ever Need' (tlsywen) 1.1.0-RC1 requires version 17 or later of 'OpenJDK 64-Bit Server VM' (java), but only the wrong version is present: 16!
	at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:51)
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:192)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:148)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

**Comment by QueenOfSquiggles** [comment]
Sure thing. The error log does recommend a potential solution:
`- Replace 'OpenJDK 64-Bit Server VM' (java) 16 with version 17 or later.`
Simply what this means is that I wrote the code using a JDK version of 17 or later (I think I used 17 but can't quite remember.) 
If you are trying to run the mod, you need to update your Java Runtime to be version 17 compatible (so 17 or higher).
If you are developing based off this mod, you need to make sure your Runtime and Development Kits are both 17 compatible. 

I can't really give more recommendations without more information. But I highly suspect that it is a version mismatch. Since you are using OpenJDK, here's the [latest available](https://openjdk.org/projects/jdk/20/) (which is always a good idea for security concerns)

Also, I'm going to close this issue. If problems persist, I can almost guarantee you will have a different error, which I would like in a different issue. Thanks for reaching out to me. I hope this helps!
